### ISSUE TITLE
During training how did you assign dead track to dead label ? 

### ISSUE THREAD

**Issue by JarveeLee** [OpenDriveLab/UniAD#117]
https://github.com/OpenDriveLab/UniAD/blob/main/projects/mmdet3d_plugin/losses/track_loss.py#L417
unmatched_track_idxes = full_track_idxes[track_instances.obj_idxes == -1]

Hello, the implementation here confused me. Because I think during training there exists two types of track in unmatched_track_idxes:
1, The dead tracks from previous frame, shall be assigned to dead state during training.
2, The new tracks from current frame, shall be assigned to the remaining labels left by active tracks. 

If we equally use the two types of track to match labels in current gt, trained in this way. Then I guess a track from previous frame, shall be dead now, would switch to another object with different id. I did not find code that assigned the dead track to dead label. 

I am not sure the correctness of such assumption.

**Comment by ilnehc** [comment]
@JarveeLee The implementation follows the original MOTR (https://github.com/megvii-research/MOTR/blob/8690da3392159635ca37c31975126acf40220724/models/motr.py#L213). The `track_instances.obj_idxes == -1` does not include disappeared tracks (their obj_idxes are kept instead of being assigned -1 during training).
