### ISSUE TITLE
Do not understand non-linear Optim in MotionFormer

### ISSUE THREAD

**Issue by Naive-Bayes** [OpenDriveLab/UniAD#16]
As Eq (5) in paper, what is the difference between two L-2 term. In my opinion, X_T just a part of X, the first term is a parallel format of the second term in time level.

**Comment by YTEP-ZHI** [comment]
Yes, but we add the special term at time T to ensure that the end-point of new-gt is close to the original gt. Otherwise, the optimized new-gt could be far away from the destination.

**Comment by Naive-Bayes** [comment]
Thanks for your quickly reply!
There remain some confusion: what does we want to optimize,  the prediction results x from motionformer, or the gt_traj of agent?
(1) if are prediction results, why do we use non-linear optimizer in inference time?
(2) if are gt_traj, they are actually physically feasible, why do we need to add addition optimization?

By the way, UniAD is a really great work!

############### in chinese #####################
我们通过非线性优化，想优化的到底是什么，如果是motionformer从motion query解出来的预测结果，那么我们在推理阶段也应该加上这个非线性优化；如果优化的是GT，GT已经是物理世界中真实发生的了，说明是符合物理学规律的（物理上可以实现的），那我们为什么要多加一个对GT做优化的过程呢？

**Comment by YTEP-ZHI** [comment]
Hi @Naive-Bayes, thanks for your question. I think this illustration would solve your doubts about nonlinear optimiztation.
![image](https://user-images.githubusercontent.com/48089846/235044371-91f67b7f-7cc3-4376-bf24-087b2b88c3f9.png)

You see, that trajectories are actually sequential waypoints starting from a bounding box. If the bounding box is correctly located as gt_bbox, we should directly learn the gt_traj as you pointed out. 
However, UniAD is an end-to-end system. The input bounding box for motion module is **not gt_bbox** but the **pred_bbox** from upstream tracking module, and the pred_bbox is usually located differently with gt_bbox (as well as heading angle and other attributes).
Starting from the pred_bbox with upstream error, it may not be a good idea to continuely model the original trajectory, since:
 * It may lead the ego-car to wrong destination.
 * It may be physically infeasible at current heading angle.

Therefore, we optimize the gt_traj in training to make the optimized_traj physically smooth and make the end-point close to the original destination.

**Comment by YTEP-ZHI** [comment]
I'm closing this issue as there's no further conversations, feel free to reopen it if needed @Naive-Bayes .
