### ISSUE TITLE
Question about difference bev_size - 50 or 100

### ISSUE THREAD

**Issue by jtengyp** [OpenDriveLab/UniAD#33]
The configs only provide bev size of 200x200.  I'm trying difference bev size, like 100x100, or 50x50.

I noticed that in [NuScenesE2EDataset](https://github.com/OpenDriveLab/UniAD/blob/main/projects/mmdet3d_plugin/datasets/nuscenes_e2e_dataset.py#L97), the canvas_size only supports 50 and 200. 

While in [UniADTrack->upsample_bev_if_tiny](https://github.com/OpenDriveLab/UniAD/blob/main/projects/mmdet3d_plugin/uniad/detectors/uniad_track.py#L589), the bev_size only supports 100x100.

Now I'm confused about bev size of 50 and 100. Or the bev size of 50 does not need to upsample in UniADTrack->upsample_bev_if_tiny?

**Comment by YTEP-ZHI** [comment]
Hi, @jtengyp. In our implementation, for uniad-small with 100x100 bev size, we actually train the perception heads(track_map) on top of the 100x100 bev plane, then the bev feature is upsampled to 200x200 for prediction and planning heads. That's why the upsample_bev_if_tiny function is needed. 
We will release the configs for uniad-small soon, which is an example of how to adapt to smaller bev.

**Comment by jtengyp** [comment]
@YTEP-ZHI  Will the configs for uniad-small be released?

**Comment by YTEP-ZHI** [comment]
Hi @jtengyp, as we have other projects going on, we may not be available to release other model variants in the near future.
